services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.29.0
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - ~/Documents/weaviate_data:/var/lib/weaviate # Change this to your desired path! First path is the host path, second path is the container path
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate" # Change this to your desired path with the same path as the volume
      ENABLE_API_BASED_MODULES: "true"
      CLUSTER_HOSTNAME: "node1"
